name: Automated Issue Management

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, synchronize, closed ]

jobs:
  auto-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Debug
        run: echo "Workflow triggered!"