name: Start Workspace On Issue Creation or Comment
on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest
    environment: start-ai-workspace
    steps:
      - name: Start Coder workspace
        uses: abhaygha/amdocs-cde-task@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: >-
            ${
              (github.event_name == 'issue_comment' && github.event.comment.user.login) || 
              (github.event_name == 'issues' && github.event.issue.user.login)
            }
          coder-url: https://coder.eks.cde.dev.srcd.io/
          coder-token: ${{ secrets.CODER_TOKEN }}
          template-name: devops-engineer-template
          parameters: |-
            Coder Image: codercom/oss-dogfood:latest
            Coder Repository Base Directory: "~"
            AI Code Prompt: "Use the gh CLI tool to read the details of issue https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }} and then address it."
            Region: us-pittsburgh