name: Automated Monitoring

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Dev Environment Health
        run: |
          if ! curl -sf https://coder.eks.cde.dev.srcd.io/health; then
            gh issue create --title "Dev Environment Down" --body "Automated health check failed." --label "incident"
          fi