name: Automated Rollback

on:
  workflow_run:
    workflows: ["Automated Environment Promotion"]
    types: [ completed ]

jobs:
  auto-rollback:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Auto Rollback
      run: |
        echo "Automatically rolling back to previous version"
        # Get previous successful deployment
        PREVIOUS_VERSION=$(git describe --tags --abbrev=0 HEAD~1)
        
        # Rollback all environments
        for env in dev staging prod; do
          terraform init
          terraform apply -auto-approve -var-file=environments/$env.tfvars -var="version=$PREVIOUS_VERSION"
        done
    
    - name: Auto Notify Rollback
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '   Automated Rollback Executed',
            body: `A deployment failure triggered an automatic rollback to the previous stable version.
            
            - **Failed Version**: ${{ github.sha }}
            - **Rollback Version**: $PREVIOUS_VERSION
            - **Time**: ${new Date().toISOString()}
            
            Please investigate the deployment failure.`,
            labels: ['rollback', 'auto-generated', 'urgent']
          });