name: Verify Build

on:
  push:
    branches: [ main, ts-refactor ]
  pull_request:
    branches: [ main ]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install dependencies
        run: bun install
      
      - name: Verify build is up to date
        run: bash scripts/verify-build.sh